### ISSUE TITLE
Spelling Mistakes?

### ISSUE THREAD

**Issue by conanyangqun** [open-source-for-science/TensorFlow-Course#20]
Find a spelling mistake in this doc [https://github.com/open-source-for-science/TensorFlow-Course/tree/master/docs/tutorials/1-basics/variables](https://github.com/open-source-for-science/TensorFlow-Course/tree/master/docs/tutorials/1-basics/variables)。
**Initializing Specific Variables part**, the code I think is:
```
# The initializer
init_custom_op = tf.variables_initializer(var_list=variable_list_custom) # not all_variables_list
```
Is it right?

**Comment by astorfi** [comment]
Please create pull request for this issues.
Thanks
